site_name: fdu的ds小窝
site_description: '一个分享复旦大学大数据学院二手书和课程资料的网站'
site_author: 'FDU DSers'

theme:
  name: material
  language: zh
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - comments
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/cedric1902666/fudan-ds-info
repo_name: 'cedric1902666/fudan-ds-info'

nav:
  - 首页: index.md
  - 关于本站: about.md
  - 二手书资料: books.md
  - 二手书货架: books-shelf.md
  - 课程资料: 
    - '所有课程': courses/index.md
    - '走近人工智能': courses/aib110003-zou-jin-ren-gong-zhi-neng.md
    - '本科生科研实践': courses/comp130194-ben-ke-sheng-ke-yan-shi-jian.md
    - '数值算法与案例分析I': courses/data130002-shu-zhi-suan-fa-yu-an-li-fen-xi-i.md
    - '数值算法与案例分析I（H）': courses/data130002h-shu-zhi-suan-fa-yu-an-li-fen-xi-h.md
    - '统计（机器）学习概论': courses/data130003-tong-ji-ji-qi-xue-xi-gai-lun.md
    - '社交网络挖掘': courses/data130007-she-jiao-wang-luo-wa-jue.md
    - '人工智能': courses/data130008-ren-gong-zhi-neng.md
    - '高级大数据解析': courses/data130014-gao-ji-da-shu-ju-jie-xi.md
    - '生产实习': courses/data130016-sheng-chan-shi-xi.md
    - '数据结构': courses/data130023-shu-ju-jie-gou.md
    - '算法与数据结构（H）': courses/data130023h-suan-fa-yu-shu-ju-jie-gou-h.md
    - '概率论基础': courses/data130024-gai-lv-lun-ji-chu.md
    - '计算机原理': courses/data130025-ji-suan-ji-yuan-li.md
    - '计算理论': courses/data130031-ji-suan-li-lun.md
    - '高等线性代数': courses/data130042-gao-deng-xian-xing-dai-shu.md
    - '多元统计分析': courses/data130044-duo-yuan-tong-ji-fen-xi.md

extra:
  giscus:
    repo: cedric1902666/fudan-ds-info
    category: Comments